general:
steps:
 gctsDeploy:
 host: "https://tst.opensap.consarea.com:44300"
 client: "100"
 abapCredentialsId: "M5AMJXPQ_Credentials"
 repository: "alrikx-workbench"
 remoteRepositoryURL: "https://github.com/alrikx/workbench"
 role: "SOURCE"
 vSID: "M5A"
 verbose: true
 type: "GITHUB"
 rollback: false
